/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BankModal: typeof import('./src/components/Modal/BankModal.vue')['default']
    Breadcrumb: typeof import('./src/components/Breadcrumb.vue')['default']
    DynamicSearchForm: typeof import('./src/components/DynamicSearchForm.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    PermissionAccordion: typeof import('./src/components/PermissionAccordion.vue')['default']
    ReusableTable: typeof import('./src/components/ReusableTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    SidebarRight: typeof import('./src/components/SidebarRight.vue')['default']
    TransactionModal: typeof import('./src/components/Modal/TransactionModal.vue')['default']
  }
}
