/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  home: () => import("@/views/home/index.vue"),
  'system_role': () => import("@/views/management/role.vue"),
  'system_user': () => import("@/views/management/user.vue"),
  'master_brand': () => import("@/views/management/brand.vue"),
  'master_bankProvider': () => import("@/views/management/bankProvider.vue"),
  'master_counterParty': () => import("@/views/management/counterParty.vue"),
  'master_member': () => import("@/views/management/member.vue"),
  'master_bank': () => import("@/views/management/bank.vue"),
  'transaction_list': () => import("@/views/management/transaction.vue"),
};